apiVersion: v1
kind: Service
metadata:
  name: calculation-service
spec:
  selector:
    app: calculation-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculation-service
  template:
    metadata:
      labels:
        app: calculation-service
    spec:
      containers:
      - name: calculation-service
        image: calculation-service:latest
        imagePullPolicy: Never
        env:
        - name: JAEGER_ENDPOINT
          value: "jaeger:4317"
        - name: SERVICE_NAME
          value: "calculation-service"
        ports:
        - containerPort: 8081
